version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/base:2023.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run: python mlops_model.py

  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run: python test_model.py

  deploy:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      CIRCLECI_SSH_KEY: $CIRCLECI_SSH_KEY
      
    docker:
      - image: cimg/base:2023.04
    steps:
      - checkout
      - setup_remote_docker
     
      - run:
          name: Build Docker image
          command: docker build -t mlops_project .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker tag mlops_project $DOCKERHUB_USERNAME/mlops_project:latest
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/mlops_project:latest
      - add_ssh_keys:
          fingerprints:
            - "1Cl/ZwMCqW6VslHJuSH/p5Z4QMZ2ubv5jbpjK0K3L5g"
      - run:
          name: Deploy to EC2
          command: |
            ssh -i $CIRCLECI_SSH_KEY ubuntu@43.204.141.230 "docker pull $DOCKERHUB_USERNAME/mlops_project:latest"
            ssh -i $CIRCLECI_SSH_KEY ubuntu@43.204.141.230 "docker stop mlops_project || true && docker rm mlops_project || true"
            ssh -i $CIRCLECI_SSH_KEY ubuntu@43.204.141.230 "docker run -d -p 80:80 mlops_project:latest"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
